✅ Why NumPy?

Faster than Python lists for numerical tasks.

Supports large datasets (used in ML, AI, Data Science).

Provides vectorization (no need for loops).

In [1]:
#Create a NumPy Array
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [5]:
#2*3 matrics
zeros = np.zeros((2, 3))      
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
#array operation
a=np.array([1, 2, 3])
b=np.array([4, 5, 6])
print(a+b)   
print(a*b)  
print(a**2)  

[5 7 9]
[ 4 10 18]
[1 4 9]


In [21]:
arr=np.array([21,10,5,2004,2001])
print(np.mean(arr))  
print(np.max(arr))    
print(np.min(arr)) 
print(np.median(arr)) 
print(np.sum(arr))    

808.2
2004
5
21.0
4041


In [24]:
arr=np.array([10, 20, 30, 40])
print(arr>20)     
print(arr[arr>20])
print(arr[arr<20])

[False False  True  True]
[30 40]
[10]


In [26]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(np.split(arr, 3))
print(np.split(arr, 2)) 

[array([10, 20]), array([30, 40]), array([50, 60])]
[array([10, 20, 30]), array([40, 50, 60])]


In [28]:
a = np.array([1, 2, 3])
print(np.vstack((a))) 
print(np.hstack((a)))

[[1]
 [2]
 [3]]
[1 2 3]


In [29]:
arr = np.array([100,101,102,103,104,105])
print(arr[0])     
print(arr[-1])    
print(arr[1:4])

100
105
[101 102 103]


In [30]:
#sorting
arr = np.array([3, 1, 4, 2])
print(np.sort(arr)) 
arr2 = np.array([[3, 1], [4, 2]])
print(np.sort(arr2, axis=1))  


[1 2 3 4]
[[1 3]
 [2 4]]


~Key Features
    Arrays → 1D, 2D, 3D arrays for data storage.
    Mathematical operations → element-wise arithmetic, matrix multiplication.
    Statistical functions → mean, sum, min, max, standard deviation.
    Random numbers → simulations, dice rolls, ML datasets.
    Slicing & indexing → filtering and accessing data easily.
    Reshaping / stacking / splitting → prepare datasets for analysis.
    Linear algebra → determinant, inverse, dot product for ML/AI.
    Broadcasting → perform operations on arrays of different shapes efficiently.

~Real-World Applications
    Student Marks Analyzer → calculate total, average, grades.
    Stock Price Simulation → cumulative changes, trends.
    Weather Data Analysis → temperature trends, filtering extreme values.
    Image Processing → pixel manipulation using 2D/3D arrays.
    Machine Learning → all ML models rely on NumPy for numerical computations.

In [35]:
import numpy as np

np.random.seed(0)
scores = np.random.randint(0, 101, size=(1000, 5))
total = np.sum(scores, axis=1)
average = np.mean(scores, axis=1)
pass_count = np.sum(average >= 50)
top5_indices = np.argsort(average)[-5:][::-1]
top5_scores = scores[top5_indices]
print("Number of students passed:", pass_count)
print("Top 5 students' scores:\n", top5_scores)


Number of students passed: 495
Top 5 students' scores:
 [[ 86  95  89  92  77]
 [ 92  92  69  73 100]
 [ 54  96 100  82  87]
 [ 59  83  88  88  99]
 [ 99  87  37  93  90]]
